-- SIVAKAR DIWALI 2026 - SUPABASE SCHEMA
-- Import supabase/seed_products.csv after creating the products table.

create table if not exists public.products (
  id integer primary key,
  category text not null,
  name text not null,
  catalog_unit text,
  stock_units integer not null default 1000 check (stock_units >= 0),
  units_per_box integer not null default 10 check (units_per_box > 0),
  box_price numeric(12,2) not null default 0 check (box_price >= 0),
  image_file text not null,
  media_file text,
  active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_no text unique not null,
  customer_name text not null,
  customer_phone text not null,
  customer_address text,
  notes text,
  items jsonb not null,
  total numeric(12,2) not null default 0,
  status text not null default 'PLACED',
  created_at timestamptz not null default now()
);

create index if not exists products_category_idx on public.products(category);
create index if not exists orders_created_at_idx on public.orders(created_at desc);

-- Derived values used by both pages.
create or replace function public.product_view()
returns table (
  id integer, category text, name text, catalog_unit text, stock_units integer,
  units_per_box integer, stock_boxes integer, stock_remainder integer,
  box_price numeric, piece_price numeric, image_file text, media_file text, active boolean
) language sql stable as $$
  select p.id,p.category,p.name,p.catalog_unit,p.stock_units,p.units_per_box,
         floor(p.stock_units / p.units_per_box)::integer,
         mod(p.stock_units,p.units_per_box),p.box_price,
         round(p.box_price / p.units_per_box,2),p.image_file,p.media_file,p.active
  from public.products p where p.active=true order by p.id;
$$;

-- Atomic admin update: boxes are the input, internal stock is recalculated.
create or replace function public.set_stock_boxes(p_id integer,p_boxes integer)
returns void language plpgsql security definer set search_path=public as $$
declare v_units integer;
begin
  if p_boxes < 0 then raise exception 'Boxes cannot be negative'; end if;
  update products set stock_units=p_boxes*units_per_box,updated_at=now() where id=p_id;
  if not found then raise exception 'Product not found'; end if;
end; $$;

-- Atomic admin update for units-per-box. The current whole-box quantity is preserved.
create or replace function public.set_units_per_box(p_id integer,p_units integer)
returns void language plpgsql security definer set search_path=public as $$
declare v_boxes integer;
begin
  if p_units <= 0 then raise exception 'Units per box must be greater than zero'; end if;
  select floor(stock_units / units_per_box)::integer into v_boxes from products where id=p_id;
  if v_boxes is null then raise exception 'Product not found'; end if;
  update products set units_per_box=p_units,stock_units=v_boxes*p_units,updated_at=now() where id=p_id;
end; $$;

create or replace function public.set_box_price(p_id integer,p_price numeric)
returns void language plpgsql security definer set search_path=public as $$
begin
  if p_price < 0 then raise exception 'Price cannot be negative'; end if;
  update products set box_price=round(p_price,2),updated_at=now() where id=p_id;
  if not found then raise exception 'Product not found'; end if;
end; $$;

-- Customer order: validates stock and decrements atomically.
create or replace function public.place_order(p_customer_name text,p_customer_phone text,p_address text,p_notes text,p_items jsonb,p_total numeric)
returns text language plpgsql security definer set search_path=public as $$
declare
  x jsonb; v_id integer; v_qty integer; v_unit text; v_units integer; v_order text; v_total numeric:=0;
  v_box_price numeric; v_upb integer; v_stock integer;
begin
  if coalesce(trim(p_customer_name),'')='' or coalesce(trim(p_customer_phone),'')='' then raise exception 'Customer name and phone are required'; end if;
  if jsonb_array_length(p_items)=0 then raise exception 'Order is empty'; end if;
  for x in select * from jsonb_array_elements(p_items) loop
    v_id := (x->>'id')::integer; v_qty := (x->>'qty')::integer; v_unit := upper(x->>'unit');
    if v_qty <= 0 then raise exception 'Invalid quantity'; end if;
    select stock_units,units_per_box,box_price into v_stock,v_upb,v_box_price from products where id=v_id and active=true for update;
    if not found then raise exception 'Product unavailable: %',v_id; end if;
    v_units := case when v_unit='BOX' then v_qty*v_upb else v_qty end;
    if v_units > v_stock then raise exception 'Insufficient stock for product %',v_id; end if;
    update products set stock_units=stock_units-v_units,updated_at=now() where id=v_id;
    v_total := v_total + case when v_unit='BOX' then v_qty*v_box_price else v_qty*round(v_box_price/v_upb,2) end;
  end loop;
  v_order := 'SIV-'||to_char(now(),'YYMMDDHH24MISS')||'-'||lpad((floor(random()*10000))::int::text,4,'0');
  insert into orders(order_no,customer_name,customer_phone,customer_address,notes,items,total) values(v_order,trim(p_customer_name),trim(p_customer_phone),p_address,p_notes,p_items,round(v_total,2));
  return v_order;
end; $$;

-- Development-friendly permissions. Before public launch, tighten admin RPC access with Supabase Auth/RLS.
alter table public.products enable row level security;
alter table public.orders enable row level security;
drop policy if exists products_public_read on public.products;
create policy products_public_read on public.products for select using (active=true);
drop policy if exists orders_public_insert on public.orders;
create policy orders_public_insert on public.orders for insert with check (true);

grant select on public.products to anon,authenticated;
grant insert on public.orders to anon,authenticated;
grant execute on function public.product_view() to anon,authenticated;
grant execute on function public.place_order(text,text,text,text,jsonb,numeric) to anon,authenticated;
grant execute on function public.set_stock_boxes(integer,integer) to anon,authenticated;
grant execute on function public.set_units_per_box(integer,integer) to anon,authenticated;
grant execute on function public.set_box_price(integer,numeric) to anon,authenticated;

-- CSV import mapping: import stock_boxes from CSV as a temporary step, then run:
-- update products set stock_units = stock_boxes * units_per_box;
-- The supplied admin page uses the RPCs for future edits.
